=== AnthonyChyrko/TAT_JAVA_Chyrko_Task4/TAT_JAVA_Chyrko_Task4/bin/commandList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.library.epam.com/commandList" 
	xmlns:tns="http://www.library.epam.com/commandList" 
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	
	<element name="commandList">
		<complexType>
			<sequence>
				<element name="command" type="tns:CommandType" minOccurs="1" maxOccurs="15" />
			</sequence>		
		</complexType>	
	</element>
	
	<complexType name="CommandType">
		<sequence>			
			<element name="path" type="tns:PathType" minOccurs="1"/>						
		</sequence>
		 <attribute name="name" type="string" use="required"/>
	</complexType>		
    
    <simpleType name="PathType">
        <restriction base="string">
            <pattern value="com.epam.library.controller.command.impl.[-_a-zA-Z]+"/>
        </restriction>
    </simpleType>	
</schema>

=== AnthonyChyrko/TAT_JAVA_Chyrko_Task4/TAT_JAVA_Chyrko_Task4/bin/commandList.xml
<?xml version="1.0" encoding="UTF-8"?>
<commandList xmlns ="http://www.library.epam.com/commandList"
            xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.library.epam.com/commandList commandList.xsd">    
    	<command name="Add_Book">    		
    		<path>com.epam.library.controller.command.impl.AddBook</path>
    	</command>
    	
    	<command name="Add_Subscription">    		
    		<path>com.epam.library.controller.command.impl.AddSubscription</path>
    	</command>
    	
    	<command name="Ban_User">    		
    		<path>com.epam.library.controller.command.impl.BanUser</path>    	
    	</command>
    	
    	<command name="Book_Availability">    		
    		<path>com.epam.library.controller.command.impl.BookAvailability</path>    	
    	</command>
    	
    	<command name="Edit_Access">    		
    		<path>com.epam.library.controller.command.impl.EditAccess</path>    	
    	</command>
    	
    	<command name="Edit_Book">    		
    		<path>com.epam.library.controller.command.impl.EditBook</path>
    	</command>
    	
    	<command name="Edit_Login">    		
    		<path>com.epam.library.controller.command.impl.EditLogin</path>    	
    	</command>
    	
    	<command name="Edit_Order_Books_List">    		
    		<path>com.epam.library.controller.command.impl.EditOrderBooksList</path>    	
    	</command>
    	
    	<command name="Edit_Password">    		
    		<path>com.epam.library.controller.command.impl.EditPassword</path>    	
    	</command>
    	
    	<command name="Register">    		
    		<path>com.epam.library.controller.command.impl.Register</path>    	
    	</command>
    	
    	<command name="Remove_Subscription">    		
    		<path>com.epam.library.controller.command.impl.RemoveSubscription</path>    	
    	</command>
    	
    	<command name="Show_All_Books">    		
    		<path>com.epam.library.controller.command.impl.ShowAllBooks</path>    	
    	</command>
    	
    	<command name="Sign_In">    		
    		<path>com.epam.library.controller.command.impl.SignIn</path>    	
    	</command>
    	
    	<command name="Sign_Out">    		
    		<path>com.epam.library.controller.command.impl.SignOut</path>    	
    	</command>
    	
    	<command name="Wrong_Request">    		
    		<path>com.epam.library.controller.command.impl.WrongRequest</path>    	
    	</command>
 
</commandList>
