=== AnthonyChyrko/TAT_JAVA_Chyrko_Task4/TAT_JAVA_Chyrko_Task4/src/commandList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.library.epam.com/commandList" 
	xmlns:tns="http://www.library.epam.com/commandList" 
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	
	<element name="commandList">
		<complexType>
			<sequence>
				<element name="command" type="tns:CommandType" minOccurs="1" maxOccurs="unbounded" />
			</sequence>		
		</complexType>	
	</element>	
	
	<simpleType name="CommandType" >	
		<restriction base="string">
			<pattern value="[a-zA-Z_]{1,42}" />
		</restriction>					
	</simpleType>
		
</schema>

=== AnthonyChyrko/TAT_JAVA_Chyrko_Task4/TAT_JAVA_Chyrko_Task4/src/commandList.xml
<?xml version="1.0" encoding="UTF-8"?>
<commandList xmlns ="http://www.library.epam.com/commandList"
            xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.library.epam.com/commandList commandList.xsd">    
    	<command>
    		<name>Add_Book</name>
    		<path>com.epam.library.controller.command.impl.AddBook</path>
    	</command>
    	<command>Add_Subscription</command>
    	<command>Ban_User</command>
    	<command>Book_Availability</command>
    	<command>Edit_Access</command>
    	<command>Edit_Book</command>
    	<command>Edit_Login</command>
    	<command>Edit_Order_Books_List</command>
    	<command>Edit_Password</command>
    	<command>Register</command>
    	<command>Remove_Subscription</command>
    	<command>Show_All_Books</command>
    	<command>Sign_In</command>
    	<command>Sign_Out</command>
    	<command>Wrong_Request</command>
 
</commandList>
