=== AnthonyChyrko/TAT_JAVA_Chyrko_Task4/TAT_JAVA_Chyrko_Task4/src/commands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.library.epam.com/commands" 
		xmlns:tns="http://www.library.epam.com/commands" 
		elementFormDefault="qualified"
		attributeFormDefault="unqualified">
	
	<element name="commands">
		<complexType>
			<sequence>
				<element name="command" type="tns:CommandType" minOccurs="1" maxOccurs="unbounded" />
			</sequence>		
		</complexType>	
	</element>
	
	<complexType name="CommandType" >		
		<all >
			<element name="title" type="tns:TitleType" minOccurs="0" maxOccurs="1"/>
			<element name="login" type="tns:LoginType" minOccurs="0" maxOccurs="1"/>
			<element name="password" type="tns:PasswordType" minOccurs="0" maxOccurs="1"/>
			<element name="author" type="tns:AuthorType" minOccurs="0" maxOccurs="1"/>			
			<element name="year" type="gYear" minOccurs="0" maxOccurs="1"/>
			<element name="genre" type="tns:GenreType" minOccurs="0" maxOccurs="1"/>
			<element name="quantity" type="nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
			<element name="availability" type="tns:AvailabilityType" minOccurs="0" maxOccurs="1"/>			
			<element name="sign_In" type="tns:SignInType" minOccurs="0" maxOccurs="1"/>			
			<element name="user_Id" type="nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
			<element name="book_Id" type="nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
			<element name="access" type="tns:AccessType" minOccurs="0" maxOccurs="1"/>
			<element name="action_Command" type="tns:ActionCommandType" minOccurs="0" maxOccurs="1"/>		
		</all>
		<attribute name="id" type="string" use="required"/>
		<attribute name="name" type="string" use="required"/>				
	</complexType>
	
	<simpleType name="TitleType">
		<restriction base="string">
			<pattern value="[a-zA-Zа-яА-ЯёЁ]{1,42}" />
		</restriction>
	</simpleType>
	
	<simpleType name="LoginType">
		<restriction base="string">
			<pattern value="[A-Za-z0-9-]{1,15}" />
		</restriction>
	</simpleType>
	
	<simpleType name="PasswordType">
		<restriction base="string">
			<pattern value="(([a-z]{1,})|([A-Z]{1,})|([0-9]{1,})){8,15}" />
		</restriction>
	</simpleType>
	
	<simpleType name="AuthorType">
		<restriction base="string">
			<pattern value="[a-zA-Zа-яА-ЯёЁ]{1,42}" />
		</restriction>
	</simpleType>
	
	<simpleType name="GenreType">
		<restriction base="string">
			<pattern value="[a-zA-Zа-яА-ЯёЁ]{1,42}" />
		</restriction>
	</simpleType>
	
	<simpleType name="AvailabilityType">
		<restriction base="string">
			<enumeration value="Y"/>
			<enumeration value="N"/>
		</restriction>
	</simpleType>
	
	<simpleType name="SignInType">
		<restriction base="string">
			<enumeration value="IN"/>
			<enumeration value="OUT"/>
			<enumeration value="BAN"/>
		</restriction>
	</simpleType>
	
	<simpleType name="AccessType">
		<restriction base="string">
			<enumeration value="N"/>
			<enumeration value="U"/>
			<enumeration value="A"/>
			<enumeration value="SA"/>
		</restriction>
	</simpleType>
	
	<simpleType name="ActionCommandType">
		<restriction base="string">
			<enumeration value="Add_book"/>
			<enumeration value="Remove_book"/>			
		</restriction>
	</simpleType>	
	
</schema>

=== AnthonyChyrko/TAT_JAVA_Chyrko_Task4/TAT_JAVA_Chyrko_Task4/src/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<commands xmlns ="http://www.library.epam.com/commands"
            xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.library.epam.com/commands commands.xsd">

	<command id = "1" name="Add_Book">
		<title>SuperBookFree</title>
		<author>Somebody</author>
		<year>2017</year>
		<genre>fantastic</genre>
		<quantity>15</quantity>
		<availability>Y</availability>			
	</command>
	
	<command id = "2" name="Add_Subscription">				
	</command>
	
	<command id = "3" name="Ban_User">		
		<login>Petr</login>
		<sign_In>BAN</sign_In>		
	</command>
	
	<command id = "4" name="Book_Availability">
		<book_Id>4</book_Id>
		<title>SuperBook</title>
		<availability>Y</availability>
		<author>Chyrko</author>
		<year>2015</year>
		<quantity>15</quantity>
		<genre>fantastik</genre>
	</command>
	
	<command id = "5" name="Edit_Access">
		<login>Petr</login>
		<access>U</access>
	</command>
	
	<command id = "6" name="Edit_Book">
		<book_Id>4</book_Id>
		<title>SuperBook</title>
		<author>Chyrko</author>
		<genre>fantastik</genre>
		<quantity>15</quantity>
	</command>
	
	<command id = "7" name="Edit_Login">
		<login>Petr</login>
	</command>
	
	<command id = "8" name="Edit_Order_Books_List">
		<action_Command>Add_book</action_Command>
		<book_Id>4</book_Id>
	</command>
	
	<command id = "9" name="Edit_Password">
		<password>newPassword123</password>
	</command>
	
	<command id = "10" name="Register">
		<login>Semas</login>
		<password>asasdsdfDFEWRTDFASDFASDFSAFSD</password>		
	</command>
	
	<command id = "11" name="Remove_Subscription">
		<user_Id>3</user_Id>
		<book_Id>6</book_Id>
	</command>
	
	<command id = "12" name="Show_All_Books">		
	</command>
	
	<command id = "13" name="Sign_In">
		<login>Anton</login>
		<access>SA</access>
	</command>
	
	<command id = "14" name="Sign_Out">
		<login>Anton</login>
	</command>
	
	<command id = "15" name="Wrong_Request">	
	</command>

</commands>
